import Link from "next/link";
import { AppShell } from "@/components/app-shell";
import { UsageIcon } from "@/components/usage-icon";
import { requireUser } from "@/lib/auth";
import { createAdminClient } from "@/lib/supabase/admin";
export const dynamic="force-dynamic";

function karachiDayStart(){const parts=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Karachi",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date());const get=(type:string)=>parts.find(part=>part.type===type)?.value||"";return new Date(`${get("year")}-${get("month")}-${get("day")}T00:00:00+05:00`).toISOString()}
function transactionLabel(type:string){return ({generation_capture:"AI generation",generation_hold:"Reserved for generation",generation_release:"Released reservation",purchase:"Credit purchase",admin_adjustment:"Support adjustment",welcome_credit:"Welcome credits"} as Record<string,string>)[type]||type.replaceAll("_"," ")}
function usageSummary(row:Record<string,unknown>|undefined){if(!row)return "—";const parts=[];if(row.input_tokens!=null)parts.push(`${row.input_tokens} input tokens`);if(row.output_tokens!=null)parts.push(`${row.output_tokens} output tokens`);if(row.characters!=null)parts.push(`${row.characters} characters`);if(row.seconds!=null)parts.push(`${row.seconds}s`);if(row.images!=null)parts.push(`${row.images} image${Number(row.images)===1?"":"s"}`);if(row.reference_images!=null)parts.push(`${row.reference_images} reference image${Number(row.reference_images)===1?"":"s"}`);return parts.join(" · ")||"Recorded usage"}
function operationLabel(metadata:unknown,generationJobId:string|null,jobs:ReadonlyArray<{id:string;modality:string}>){const value=metadata&&typeof metadata==="object"&&"operation" in metadata?String((metadata as Record<string,unknown>).operation):generationJobId?`${jobs.find(job=>job.id===generationJobId)?.modality??"media"}_generation`:"generation";return value.replaceAll("_"," ")}

export default async function UsagePage(){
  const user=await requireUser();const admin=createAdminClient();
  const [{data:tx},{data:messages},{data:jobs},{data:profile},{data:todayTx},{data:receipts},{data:quotes},{data:usageEvents}]=await Promise.all([
    admin.from("wallet_transactions").select("id,type,amount,balance_after,reference_id,metadata,created_at").eq("user_id",user.id).order("created_at",{ascending:false}).limit(100),
    admin.from("messages").select("id,model_id,provider_key,input_tokens,output_tokens,credits_charged,metadata,created_at").eq("user_id",user.id).eq("role","assistant").order("created_at",{ascending:false}).limit(50),
    admin.from("generation_jobs").select("id,public_id,modality,model_id,status,charged_credits,estimated_credits,reserved_credits,billing_quote_id,created_at,completed_at").eq("user_id",user.id).order("created_at",{ascending:false}).limit(50),
    admin.from("profiles").select("daily_spend_limit,single_generation_limit").eq("id",user.id).single(),
    admin.from("wallet_transactions").select("amount").eq("user_id",user.id).eq("type","generation_capture").gte("created_at",karachiDayStart()),
    admin.from("billing_receipts").select("id,quote_id,usage_event_id,provider_key,model_id,pricing_version,cost_status,charge_credits,message_id,generation_job_id,metadata,settled_at").eq("user_id",user.id).order("settled_at",{ascending:false}).limit(100),
    admin.from("billing_quotes").select("id,provider_key,model_id,pricing_version,pricing_status,customer_quote_credits,reservation_credits,input_dimensions,pricing_snapshot,status,expires_at,created_at").eq("user_id",user.id).order("created_at",{ascending:false}).limit(50),
    admin.from("billing_usage_events").select("id,provider_request_id,provider_task_id,input_tokens,output_tokens,reasoning_tokens,cached_input_tokens,cache_write_tokens,characters,seconds,images,reference_images,resolution,quality,mode,fps,cost_status").eq("user_id",user.id).order("created_at",{ascending:false}).limit(100)
  ]);
  const spent=(tx||[]).filter(x=>x.type==="generation_capture").reduce((a,x)=>a+Math.abs(Number(x.amount)),0);
  const byModel=new Map<string,{credits:number,requests:number}>();
  if(receipts?.length){for(const row of receipts){const key=row.model_id||"Unknown",current=byModel.get(key)||{credits:0,requests:0};current.credits+=Number(row.charge_credits||0);current.requests+=1;byModel.set(key,current)}}else{for(const row of messages||[]){const key=row.model_id||"Auto Best",current=byModel.get(key)||{credits:0,requests:0};current.credits+=Number(row.credits_charged||0);current.requests+=1;byModel.set(key,current)}for(const row of jobs||[]){const key=row.model_id||"Unknown",current=byModel.get(key)||{credits:0,requests:0};current.credits+=Number(row.charged_credits||0);current.requests+=1;byModel.set(key,current)}}
  const modelSpend=[...byModel.entries()].map(([model,value])=>({model,...value})).sort((a,b)=>b.credits-a.credits);
  const todaySpent=(todayTx||[]).reduce((sum,row)=>sum+Math.abs(Number(row.amount)),0),dailyLimit=Number(profile?.daily_spend_limit||0),singleLimit=Number(profile?.single_generation_limit||0),dailyPercent=dailyLimit?Math.min(100,(todaySpent/dailyLimit)*100):0;
  const usageById=new Map((usageEvents||[]).map(row=>[row.id,row]));const receiptByQuote=new Map((receipts||[]).map(row=>[row.quote_id,row]));const receiptedMessageIds=new Set((receipts||[]).map(row=>row.message_id).filter(Boolean));const legacyMessages=(messages||[]).filter(row=>{const metadata=row.metadata&&typeof row.metadata==="object"?row.metadata as Record<string,unknown>:{};return row.credits_charged!=null&&!receiptedMessageIds.has(row.id)&&metadata.billingEngine!=="v3_provider_authoritative"&&!metadata.billingQuoteId&&!metadata.billingStatus});
  const metrics=[{label:"AI spend",value:spent.toFixed(2),note:"Credits",icon:"coins" as const,tone:"cyan"},{label:"Billing receipts",value:receipts?.length||0,note:"Text, audio & media",icon:"file" as const,tone:"violet"},{label:"Media jobs",value:jobs?.length||0,note:"Images, video & audio",icon:"image" as const,tone:"green"},{label:"Credit value",value:"Rs1",note:"per Credit",icon:"wallet" as const,tone:"amber"}];
  return <AppShell><main className="usage-page">
    <header className="usage-hero"><div><div className="kicker">Usage &amp; receipts</div><h1>Every credit is traceable.</h1><p>Text and media receipts show what you used and what Models Suite charged, without exposing wholesale supplier costs.</p></div><aside className="usage-hero-note"><span><UsageIcon name="chart" /></span><p><b>Transparent usage.</b><small>Smarter creativity.</small></p></aside></header>
    <section className="usage-stats" aria-label="Usage summary">{metrics.map(({label,value,note,icon,tone})=><article className={`usage-metric ${tone}`} key={label}><span><UsageIcon name={icon} /></span><div><small>{label}</small><strong>{value}</strong><em>{note}</em></div></article>)}</section>
    <section className="card panel-block spending-safety"><header className="usage-section-head"><div className="usage-section-title"><span><UsageIcon name="shield" /></span><div><div className="kicker">Spending safety</div><h2>Today’s protection</h2><p>Set limits to keep your spending in control.</p></div></div><Link className="usage-limit-link" href="/settings"><UsageIcon name="gear" />Change limits</Link></header><div className="spending-safety-grid"><div><span>Spent today</span><strong>{todaySpent.toFixed(2)} Credits</strong><div className="spending-meter"><i style={{width:`${dailyPercent}%`}}/></div><small>{dailyLimit?`${Math.max(0,dailyLimit-todaySpent).toFixed(2)} remaining from ${dailyLimit.toFixed(2)} daily limit`:"No daily limit set"}</small></div><div><span>Per generation</span><strong>{singleLimit?`${singleLimit.toFixed(2)} Credits`:"No limit set"}</strong><small>Requests above this amount are blocked before wallet reservation.</small></div></div></section>
    <section className="card panel-block usage-model-spend"><header className="usage-section-head"><div className="usage-section-title"><span><UsageIcon name="chart" /></span><div><div className="kicker">Cost explorer</div><h2>Spend by model</h2><p>See which models use the most credits based on completed usage.</p></div></div><span className="usage-completed">Actual completed usage</span></header>{modelSpend.length?<div className="cost-bars">{modelSpend.slice(0,10).map(row=><div className="cost-row" key={row.model}><div><b>{row.model}</b><span>{row.requests} request{row.requests===1?"":"s"}</span></div><div className="cost-track"><i style={{width:`${Math.max(3,(row.credits/Math.max(...modelSpend.map(item=>item.credits),1))*100)}%`}}/></div><strong>{row.credits.toFixed(2)} cr</strong></div>)}</div>:<p className="muted">Cost distribution appears after your first completed generation.</p>}</section>
    <section className="card panel-block usage-receipts"><header className="usage-section-head"><div className="usage-section-title"><span><UsageIcon name="receipt" /></span><div><div className="kicker">Wallet receipts</div><h2>Final billing receipts</h2><p>One server-settled record for every completed text, prompt, TTS, audio, image, and video operation.</p></div></div><span className="usage-completed">Exact final charge</span></header><div className="table-wrap"><table><thead><tr><th>Settled</th><th>Operation</th><th>Model</th><th>Provider</th><th>Usage</th><th>Pricing version</th><th>Cost basis</th><th>Final charge</th><th>Receipt</th></tr></thead><tbody>{receipts?.length?receipts.map(r=>{const usage=usageById.get(r.usage_event_id) as Record<string,unknown>|undefined;return <tr key={r.id}><td>{new Date(r.settled_at).toLocaleString()}</td><td>{operationLabel(r.metadata,r.generation_job_id,jobs||[])}</td><td>{r.model_id}</td><td>{r.provider_key}</td><td>{usageSummary(usage)}</td><td><code>{r.pricing_version}</code></td><td><span className="badge">{r.cost_status.replaceAll("_"," ")}</span></td><td><b>{Number(r.charge_credits).toFixed(4)} Credits</b></td><td><code>{r.id.slice(0,8)}</code></td></tr>}):<tr><td colSpan={9}>No final billing receipts yet.</td></tr>}</tbody></table></div></section>
    <section className="card panel-block usage-receipts"><header className="usage-section-head"><div className="usage-section-title"><span><UsageIcon name="shield" /></span><div><h2>Server-generated quotes &amp; reservations</h2><p>Reservations are temporary wallet holds, not charges. Variable usage shows an estimate until the final receipt is settled.</p></div></div></header><div className="table-wrap"><table><thead><tr><th>Created</th><th>Model / provider</th><th>Pricing</th><th>Quote type</th><th>Estimated quote</th><th>Reserved</th><th>Status</th><th>Final charge</th></tr></thead><tbody>{quotes?.length?quotes.map(q=>{const snapshot=q.pricing_snapshot as Record<string,unknown>;const quoteKind=String(snapshot?.quoteKind??snapshot?.quote_kind??"variable");const finalReceipt=receiptByQuote.get(q.id);const released=!finalReceipt&&["cancelled","expired","released"].includes(q.status);return <tr key={q.id}><td>{new Date(q.created_at).toLocaleString()}</td><td><b>{q.model_id}</b><div className="muted small">{q.provider_key}</div></td><td><code>{q.pricing_version}</code><div className="muted small">{q.pricing_status}</div></td><td>{quoteKind==="deterministic"?"Fixed":"Variable estimate"}</td><td>{Number(q.customer_quote_credits).toFixed(4)} Credits</td><td>{Number(q.reservation_credits).toFixed(4)} Credits<div className="muted small">temporary hold</div></td><td><span className="badge">{released?"Released":finalReceipt?"settled":"Billing pending"}</span></td><td>{finalReceipt?<b>{Number(finalReceipt.charge_credits).toFixed(4)} Credits</b>:released?"No charge":"Billing pending"}</td></tr>}):<tr><td colSpan={8}>No server-generated quotes yet.</td></tr>}</tbody></table></div></section>
    {legacyMessages.length>0&&<section className="card panel-block usage-receipts"><header className="usage-section-head"><div className="usage-section-title"><span><UsageIcon name="receipt" /></span><div><h2>Historical billing</h2><p>Legacy text records created before current final-receipt settlement.</p></div></div></header><div className="table-wrap"><table><thead><tr><th>Date</th><th>Model</th><th>Provider</th><th>Input</th><th>Output</th><th>Charged</th></tr></thead><tbody>{legacyMessages.map(r=><tr key={r.id}><td>{new Date(r.created_at).toLocaleString()}</td><td>{r.model_id}</td><td>{r.provider_key||"—"}</td><td>{r.input_tokens??"—"}</td><td>{r.output_tokens??"—"}</td><td>{Number(r.credits_charged||0).toFixed(4)} Credits</td></tr>)}</tbody></table></div></section>}
    <section className="card panel-block usage-receipts"><header className="usage-section-head"><div className="usage-section-title"><span><UsageIcon name="image" /></span><div><h2>Media generation activity</h2><p>Current image, video, and audio jobs with temporary reservations and exact final charges.</p></div></div></header><div className="table-wrap"><table><thead><tr><th>Date</th><th>Reference</th><th>Type</th><th>Model</th><th>Status</th><th>Temporary reservation</th><th>Final charge</th><th>Open</th></tr></thead><tbody>{jobs?.length?jobs.map(r=><tr key={r.id}><td>{new Date(r.created_at).toLocaleString()}</td><td>{r.public_id}</td><td>{r.modality}</td><td>{r.model_id}</td><td><span className="badge">{r.status}</span></td><td>{["completed","failed","cancelled","expired"].includes(r.status)?"Released":`${Number(r.reserved_credits||0).toFixed(4)} Credits`}</td><td>{["completed","failed","cancelled","expired"].includes(r.status)?`${Number(r.charged_credits||0).toFixed(4)} Credits`:"Billing pending"}</td><td><Link className="link-button" href={r.modality === "image" ? "/images" : r.modality === "video" ? "/video" : "/audio"}>Open studio</Link></td></tr>):<tr><td colSpan={8}>No media activity yet.</td></tr>}</tbody></table></div></section>
    <section className="card panel-block usage-receipts"><header className="usage-section-head"><div className="usage-section-title"><span><UsageIcon name="wallet" /></span><div><h2>Wallet receipts</h2><p>Immutable ledger entries for every credit movement.</p></div></div><span className="usage-completed">1 Credit = PKR 1</span></header><div className="table-wrap"><table><thead><tr><th>Date</th><th>Description</th><th>Amount</th><th>Balance after</th><th>Receipt reference</th></tr></thead><tbody>{tx?.length?tx.map(r=><tr key={r.id}><td>{new Date(r.created_at).toLocaleString()}</td><td>{transactionLabel(r.type)}</td><td className={Number(r.amount)<0?"negative":"positive"}>{Number(r.amount)>=0?"+":""}{Number(r.amount).toFixed(4)} Credits</td><td>{r.balance_after==null?"—":`${Number(r.balance_after).toFixed(4)} Credits`}</td><td><code>{r.reference_id||r.id}</code></td></tr>):<tr><td colSpan={5}>No ledger entries yet.</td></tr>}</tbody></table></div></section>
  </main></AppShell>
}
