"use client";
import Link from "next/link";
import Image from "next/image";
import { type ReactNode,useEffect,useMemo,useState } from "react";
type Conversation={id:string;title:string;mode:string;preferred_model?:string;pinned:boolean;updated_at:string};
type Job={id:string;modality:string;model_id:string;status:string;prompt?:string;result_urls?:string[];charged_credits?:number;created_at:string};
type FileRow={id:string;name:string;mime_type:string;size_bytes:number;extraction_status:string;created_at:string};
type View="all"|"chat"|"image"|"video"|"audio"|"file";
export function HistoryClient({crossModalityHandoffs=false}:{crossModalityHandoffs?:boolean}){
 const [conversations,setConversations]=useState<Conversation[]>([]),[jobs,setJobs]=useState<Job[]>([]),[files,setFiles]=useState<FileRow[]>([]),[favoriteJobs,setFavoriteJobs]=useState<string[]>([]),[favoriteFiles,setFavoriteFiles]=useState<string[]>([]),[q,setQ]=useState(""),[view,setView]=useState<View>("all"),[loading,setLoading]=useState(true);
 const [detail,setDetail]=useState<{kind:"job";item:Job}|{kind:"file";item:FileRow;url?:string}|null>(null),[detailLoading,setDetailLoading]=useState(false);
 async function load(){setLoading(true);const [a,b,c,d]=await Promise.all([fetch("/api/conversations"),fetch("/api/jobs?limit=100"),fetch("/api/files"),fetch("/api/favorites")]);if(a.ok)setConversations((await a.json()).conversations||[]);if(b.ok)setJobs((await b.json()).jobs||[]);if(c.ok)setFiles((await c.json()).files||[]);if(d.ok){const data=await d.json();setFavoriteJobs(data.jobIds||[]);setFavoriteFiles(data.fileIds||[])}setLoading(false)}
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[]);
 async function patchConversation(id:string,body:Record<string,unknown>){await fetch(`/api/conversations/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});await load()}
 async function removeConversation(id:string){if(!confirm("Delete this conversation permanently?"))return;await fetch(`/api/conversations/${id}`,{method:"DELETE"});await load()}
 async function toggleFavorite(kind:"job"|"file",id:string,current:boolean){await fetch("/api/favorites",{method:current?"DELETE":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind,id})});if(kind==="job")setFavoriteJobs(items=>current?items.filter(x=>x!==id):[...items,id]);else setFavoriteFiles(items=>current?items.filter(x=>x!==id):[...items,id])}
 async function openFileDetail(item:FileRow){setDetail({kind:"file",item});setDetailLoading(true);const response=await fetch(`/api/files/${encodeURIComponent(item.id)}`);const data=await response.json().catch(()=>({}));if(response.ok&&data.file?.url)setDetail({kind:"file",item,url:data.file.url});setDetailLoading(false)}
 const needle=q.trim().toLowerCase();
 const chats=useMemo(()=>conversations.filter(x=>(view==="all"||view==="chat")&&(!needle||`${x.title} ${x.preferred_model||""}`.toLowerCase().includes(needle))),[conversations,view,needle]);
 const media=useMemo(()=>jobs.filter(x=>(view==="all"||view===x.modality)&&(!needle||`${x.prompt||""} ${x.model_id}`.toLowerCase().includes(needle))),[jobs,view,needle]);
 const uploads=useMemo(()=>files.filter(x=>(view==="all"||view==="file")&&(!needle||x.name.toLowerCase().includes(needle))),[files,view,needle]);
 const total=chats.length+media.length+uploads.length;
 return <div className="library-shell"><div className="library-tools"><div className="library-search">⌕<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search chats, prompts, models and files…"/></div><div className="library-filters">{(["all","chat","image","video","audio","file"] as View[]).map(x=><button key={x} className={view===x?"active":""} onClick={()=>setView(x)}>{x}</button>)}</div></div><div className="library-scroll">{loading?<div className="card empty-card">Loading your Library…</div>:total===0?<div className="card empty-card"><h3>Nothing matches this view</h3><p className="muted">Your reusable chats, generations and uploads appear here automatically.</p></div>:<div className="library-grid">
 {chats.map(x=><article className="card library-card" key={`chat-${x.id}`}><div className="library-type">Chat</div><Link href={`/chat?conversation=${x.id}`}><h3>{x.pinned?"★ ":""}{x.title}</h3><p>{x.preferred_model||"Auto Best"} · {new Date(x.updated_at).toLocaleDateString()}</p></Link><div className="library-actions"><button onClick={()=>patchConversation(x.id,{pinned:!x.pinned})}>{x.pinned?"Unpin":"Pin"}</button><button className="danger-text" onClick={()=>removeConversation(x.id)}>Delete</button></div></article>)}
 {media.map(x=>{const url=Array.isArray(x.result_urls)?x.result_urls[0]:undefined,studio=x.modality==="image"?"/images":`/${x.modality}`,favorite=favoriteJobs.includes(x.id);return <article className="card library-card" key={`job-${x.id}`}><button className={`favorite-button ${favorite?"active":""}`} aria-label={favorite?"Remove from favorites":"Add to favorites"} onClick={()=>toggleFavorite("job",x.id,favorite)}>★</button><div className="library-type">{x.modality} · {x.status}</div><h3>{x.prompt?.slice(0,90)||x.model_id}</h3><p>{x.model_id} · {Number(x.charged_credits||0).toFixed(2)} credits</p><div className="library-actions"><button onClick={()=>setDetail({kind:"job",item:x})}>Details</button>{url&&<a href={url} target="_blank" rel="noreferrer">Open</a>}<Link href={`${studio}?prompt=${encodeURIComponent(x.prompt||"")}`}>Use again</Link>{url&&<button onClick={()=>navigator.clipboard?.writeText(url)}>Copy link</button>}</div></article>})}
 {uploads.map(x=>{const favorite=favoriteFiles.includes(x.id),isImage=x.mime_type.startsWith("image/");return <article className="card library-card" key={`file-${x.id}`}><button className={`favorite-button ${favorite?"active":""}`} aria-label={favorite?"Remove from favorites":"Add to favorites"} onClick={()=>toggleFavorite("file",x.id,favorite)}>★</button><div className="library-type">File</div><h3>{x.name}</h3><p>{x.mime_type} · {(x.size_bytes/1024).toFixed(1)} KB · {x.extraction_status}</p><div className="library-actions"><button onClick={()=>void openFileDetail(x)}>Details</button><Link href={`/chat?file=${x.id}`}>Use in Chat</Link>{crossModalityHandoffs&&isImage&&<Link href={`/images?reference=${encodeURIComponent(x.id)}`}>Edit in Image</Link>}{crossModalityHandoffs&&isImage&&<Link href={`/video?reference=${encodeURIComponent(x.id)}`}>Animate in Video</Link>}</div></article>})}
 </div>}</div>{detail&&<AssetDetail detail={detail} loading={detailLoading} crossModalityHandoffs={crossModalityHandoffs} onClose={()=>setDetail(null)}/>}</div>
}

function AssetDetail({detail,loading,crossModalityHandoffs,onClose}:{detail:{kind:"job";item:Job}|{kind:"file";item:FileRow;url?:string};loading:boolean;crossModalityHandoffs:boolean;onClose:()=>void}){
 if(detail.kind==="job"){
  const item=detail.item,url=Array.isArray(item.result_urls)?item.result_urls[0]:undefined,mime=item.modality,studio=item.modality==="image"?"/images":`/${item.modality}`;
  return <DetailFrame title={item.prompt||item.model_id} kicker={`${item.modality} generation`} url={url} mime={mime} loading={false} onClose={onClose} metadata={[["Model",item.model_id],["Status",item.status],["Credits",Number(item.charged_credits||0).toFixed(2)],["Created",new Date(item.created_at).toLocaleString()]]}><Link href={`${studio}?prompt=${encodeURIComponent(item.prompt||"")}`}>Use again</Link>{url&&<a href={url} target="_blank" rel="noreferrer">Open original</a>}</DetailFrame>
 }
 const item=detail.item;
 return <DetailFrame title={item.name} kicker="Library file" url={detail.url} mime={item.mime_type} loading={loading} onClose={onClose} metadata={[["Type",item.mime_type],["Size",`${(item.size_bytes/1024).toFixed(1)} KB`],["Processing",item.extraction_status],["Uploaded",new Date(item.created_at).toLocaleString()]]}><Link href={`/chat?file=${item.id}`}>Use in Chat</Link>{crossModalityHandoffs&&item.mime_type.startsWith("image/")&&<Link href={`/images?reference=${encodeURIComponent(item.id)}`}>Edit in Image</Link>}{detail.url&&<a href={detail.url} target="_blank" rel="noreferrer">Open original</a>}</DetailFrame>
}

function DetailFrame({title,kicker,url,mime,loading,onClose,metadata,children}:{title:string;kicker:string;url?:string;mime:string;loading:boolean;onClose:()=>void;metadata:string[][];children:ReactNode}){
 return <div className="asset-detail-overlay" role="dialog" aria-modal="true" aria-label="Asset details"><button className="workspace-scrim" aria-label="Close asset details" onClick={onClose}/><section className="asset-detail-panel"><header><div><span className="kicker">{kicker}</span><h2>{title}</h2></div><button className="icon-button" onClick={onClose} aria-label="Close">×</button></header><div className="asset-detail-scroll"><div className="asset-preview">{loading?<span>Loading secure preview…</span>:url&&(mime==="image"||mime.startsWith("image/"))?<Image src={url} alt="Asset preview" width={1200} height={900} unoptimized/>:url&&(mime==="video"||mime.startsWith("video/"))?<video src={url} controls/>:url&&(mime==="audio"||mime.startsWith("audio/"))?<audio src={url} controls/>:<span>Preview is not available for this asset type.</span>}</div><dl className="asset-metadata">{metadata.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></div><footer>{children}</footer></section></div>
}

