"use client";

import Link from "next/link";
import Image from "next/image";
import { type ReactNode, useEffect, useMemo, useState } from "react";
import { ArrowUpRight, CaretDown, ChatCircle, ClockCounterClockwise, DotsThree, File, ImageSquare, ListBullets, MagnifyingGlass, PlayCircle, Plus, PushPin, SpeakerHigh, SquaresFour, Trash, VideoCamera, X } from "@phosphor-icons/react";

type Conversation={id:string;title:string;mode:string;preferred_model?:string;pinned:boolean;updated_at:string};
type Job={id:string;modality:string;model_id:string;status:string;prompt?:string;result_urls?:string[];charged_credits?:number;created_at:string};
type FileRow={id:string;name:string;mime_type:string;size_bytes:number;extraction_status:string;created_at:string};
type View="all"|"chat"|"image"|"video"|"audio"|"file";
type Sort="recent"|"oldest"|"pinned";
type Detail={kind:"job";item:Job}|{kind:"file";item:FileRow;url?:string};
type LibraryEntry={id:string;type:Exclude<View,"all">;date:string;pinned:boolean;item:Conversation|Job|FileRow};

const filters: {value:View; label:string}[]=[{value:"all",label:"All"},{value:"chat",label:"Chat"},{value:"image",label:"Image"},{value:"video",label:"Video"},{value:"audio",label:"Audio"},{value:"file",label:"File"}];
const formatDate=(value:string)=>new Intl.DateTimeFormat(undefined,{month:"short",day:"numeric",year:"numeric"}).format(new Date(value));
const mediaTitle=(item:Job)=>item.prompt?.trim().slice(0,88)||item.model_id||"Generated media";

export function HistoryClient({crossModalityHandoffs=false}:{crossModalityHandoffs?:boolean}){
 const [conversations,setConversations]=useState<Conversation[]>([]),[jobs,setJobs]=useState<Job[]>([]),[files,setFiles]=useState<FileRow[]>([]),[favoriteJobs,setFavoriteJobs]=useState<string[]>([]),[favoriteFiles,setFavoriteFiles]=useState<string[]>([]),[q,setQ]=useState(""),[view,setView]=useState<View>("all"),[sort,setSort]=useState<Sort>("recent"),[layout,setLayout]=useState<"grid"|"list">("grid"),[loading,setLoading]=useState(true);
 const [detail,setDetail]=useState<Detail|null>(null),[detailLoading,setDetailLoading]=useState(false);
 async function load(){setLoading(true);const [a,b,c,d]=await Promise.all([fetch("/api/conversations"),fetch("/api/jobs?limit=100"),fetch("/api/files"),fetch("/api/favorites")]);if(a.ok)setConversations((await a.json()).conversations||[]);if(b.ok)setJobs((await b.json()).jobs||[]);if(c.ok)setFiles((await c.json()).files||[]);if(d.ok){const data=await d.json();setFavoriteJobs(data.jobIds||[]);setFavoriteFiles(data.fileIds||[])}setLoading(false)}
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[]);
 async function patchConversation(id:string,body:Record<string,unknown>){await fetch(`/api/conversations/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});await load()}
 async function removeConversation(id:string){if(!confirm("Delete this conversation permanently?"))return;await fetch(`/api/conversations/${id}`,{method:"DELETE"});await load()}
 async function removeFile(id:string,name:string){if(!confirm(`Delete “${name}”? This cannot be undone.`))return;await fetch(`/api/files/${id}`,{method:"DELETE"});await load()}
 async function toggleFavorite(kind:"job"|"file",id:string,current:boolean){await fetch("/api/favorites",{method:current?"DELETE":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind,id})});if(kind==="job")setFavoriteJobs(items=>current?items.filter(x=>x!==id):[...items,id]);else setFavoriteFiles(items=>current?items.filter(x=>x!==id):[...items,id])}
 async function openFileDetail(item:FileRow){setDetail({kind:"file",item});setDetailLoading(true);const response=await fetch(`/api/files/${encodeURIComponent(item.id)}`);const data=await response.json().catch(()=>({}));if(response.ok&&data.file?.url)setDetail({kind:"file",item,url:data.file.url});setDetailLoading(false)}
 const needle=q.trim().toLowerCase();
 const matches=(value:string)=>!needle||value.toLowerCase().includes(needle);
 const allItems=useMemo<LibraryEntry[]>(()=>[
  ...conversations.map(item=>({id:`chat-${item.id}`,type:"chat" as const,date:item.updated_at,pinned:item.pinned,item})),
  ...jobs.flatMap(item=>["image","video","audio"].includes(item.modality)?[{id:`job-${item.id}`,type:item.modality as "image"|"video"|"audio",date:item.created_at,pinned:favoriteJobs.includes(item.id),item}]:[]),
  ...files.map(item=>({id:`file-${item.id}`,type:"file" as const,date:item.created_at,pinned:favoriteFiles.includes(item.id),item}))
 ],[conversations,jobs,files,favoriteJobs,favoriteFiles]);
 const counts=useMemo(()=>({all:allItems.length,chat:conversations.length,image:jobs.filter(item=>item.modality==="image").length,video:jobs.filter(item=>item.modality==="video").length,audio:jobs.filter(item=>item.modality==="audio").length,file:files.length,pinned:conversations.filter(item=>item.pinned).length+favoriteJobs.length+favoriteFiles.length}),[allItems,conversations,jobs,files,favoriteJobs,favoriteFiles]);
 const visible=useMemo(()=>allItems.filter(entry=>{
  if(view!=="all"&&entry.type!==view)return false;
  if(entry.type==="chat"){const item=entry.item as Conversation;return matches(`${item.title} ${item.preferred_model||""}`)}
  if(entry.type==="file"){const item=entry.item as FileRow;return matches(`${item.name} ${item.mime_type} ${item.extraction_status}`)}
  const item=entry.item as Job;return matches(`${item.prompt||""} ${item.model_id} ${item.status}`);
 }).sort((a,b)=>sort==="pinned"?(Number(b.pinned)-Number(a.pinned)||new Date(b.date).getTime()-new Date(a.date).getTime()):sort==="oldest"?new Date(a.date).getTime()-new Date(b.date).getTime():new Date(b.date).getTime()-new Date(a.date).getTime()),[allItems,view,needle,sort]);
 const quick=[{value:"all" as View,label:"Recent",count:counts.all,icon:ClockCounterClockwise,tone:"recent"},{value:"all" as View,label:"Pinned",count:counts.pinned,icon:PushPin,tone:"pinned",onClick:()=>setSort("pinned")},{value:"image" as View,label:"Images",count:counts.image,icon:ImageSquare,tone:"image"},{value:"video" as View,label:"Videos",count:counts.video,icon:VideoCamera,tone:"video"},{value:"audio" as View,label:"Audio",count:counts.audio,icon:SpeakerHigh,tone:"audio"},{value:"file" as View,label:"Files",count:counts.file,icon:File,tone:"file"}];
 const selectQuick=(entry:(typeof quick)[number])=>{setView(entry.value);setQ("");entry.onClick?.();if(!entry.onClick)setSort("recent")};
 return <main className="library-page premium-library-page library-redesign-page">
  <header className="library-hero"><div className="library-hero-copy"><div className="kicker">Library</div><h1>Everything you <span>create.</span></h1><p>Chats, generated media and uploaded files—searchable and reusable across every workspace.</p><Link className="library-create" href="/chat"><Plus weight="bold"/>New creation</Link></div><LibraryHeroArt/></header>
  <section className="library-shell" aria-label="Library items"><div className="library-tools"><label className="library-search"><MagnifyingGlass aria-hidden="true"/><input value={q} onChange={event=>setQ(event.target.value)} placeholder="Search chats, prompts, models and files…" aria-label="Search library"/></label><div className="library-filters" aria-label="Filter library">{filters.map(filter=><button type="button" key={filter.value} className={view===filter.value?"active":""} onClick={()=>{setView(filter.value);setSort("recent")}}>{filter.label}</button>)}</div><label className="library-sort"><span>Sort</span><select value={sort} onChange={event=>setSort(event.target.value as Sort)} aria-label="Sort library"><option value="recent">Recent first</option><option value="oldest">Oldest first</option><option value="pinned">Pinned first</option></select><CaretDown aria-hidden="true"/></label><div className="library-layout-toggle" aria-label="Choose library layout"><button type="button" className={layout==="grid"?"active":""} onClick={()=>setLayout("grid")} aria-label="Grid view"><SquaresFour weight="bold"/></button><button type="button" className={layout==="list"?"active":""} onClick={()=>setLayout("list")} aria-label="List view"><ListBullets weight="bold"/></button></div></div>
   <section className="library-quick"><h2>Quick access</h2><div>{quick.map(entry=>{const Icon=entry.icon;return <button type="button" key={entry.label} className={`quick-access ${entry.tone}`} onClick={()=>selectQuick(entry)}><span><Icon weight="fill"/></span><b>{entry.label}<small>{entry.count} item{entry.count===1?"":"s"}</small></b><ArrowUpRight aria-hidden="true"/></button>})}</div></section>
   <div className="library-scroll">{loading?<div className="library-loading" aria-live="polite"><span/><span/><span/><p>Loading your Library…</p></div>:visible.length===0?<div className="card empty-card library-empty"><i>✦</i><h3>{q||view!=="all"?"Nothing matches this view":"Your Library is ready"}</h3><p className="muted">{q||view!=="all"?"Try another search or clear the current filter.":"Your chats, generations and uploads will appear here automatically."}</p>{(q||view!=="all")&&<button type="button" onClick={()=>{setQ("");setView("all");setSort("recent")}}>Clear filters</button>}</div>:<div className={`library-grid ${layout==="list"?"is-list":""}`}>{visible.map(entry=><LibraryCard key={entry.id} entry={entry} favoriteJobs={favoriteJobs} favoriteFiles={favoriteFiles} crossModalityHandoffs={crossModalityHandoffs} onConversationPin={patchConversation} onConversationDelete={removeConversation} onFavorite={toggleFavorite} onFileDetail={openFileDetail} onFileDelete={removeFile} onJobDetail={item=>setDetail({kind:"job",item})}/>)}</div>}</div>
  </section>{detail&&<AssetDetail detail={detail} loading={detailLoading} crossModalityHandoffs={crossModalityHandoffs} onClose={()=>setDetail(null)}/>}</main>
}

function LibraryHeroArt(){return <div className="library-hero-art" aria-hidden="true"><i className="hero-orbit"/><span className="hero-media-tile image"><ImageSquare weight="duotone"/></span><span className="hero-media-tile document"><File weight="duotone"/></span><span className="hero-media-tile video"><PlayCircle weight="fill"/></span><span className="hero-media-tile audio"><SpeakerHigh weight="duotone"/></span><small>Create<br/>Save<br/>Reuse<br/>Anywhere</small></div>}

function LibraryCard({entry,favoriteJobs,favoriteFiles,crossModalityHandoffs,onConversationPin,onConversationDelete,onFavorite,onFileDetail,onFileDelete,onJobDetail}:{entry:LibraryEntry;favoriteJobs:string[];favoriteFiles:string[];crossModalityHandoffs:boolean;onConversationPin:(id:string,body:Record<string,unknown>)=>Promise<void>;onConversationDelete:(id:string)=>Promise<void>;onFavorite:(kind:"job"|"file",id:string,current:boolean)=>Promise<void>;onFileDetail:(item:FileRow)=>Promise<void>;onFileDelete:(id:string,name:string)=>Promise<void>;onJobDetail:(item:Job)=>void}){
 const {type,item}=entry;
 const TypeIcon=type==="chat"?ChatCircle:type==="image"?ImageSquare:type==="video"?VideoCamera:type==="audio"?SpeakerHigh:File;
 if(type==="chat"){const chat=item as Conversation;return <article className="card library-card library-card-chat"><CardTop type="Chat" Icon={TypeIcon}/><Link className="library-card-main" href={`/chat?conversation=${chat.id}`}><h3>{chat.title}</h3><p className="library-meta">{chat.preferred_model||"Auto Best"}<span>•</span>{formatDate(chat.updated_at)}</p><p className="library-excerpt">Open this conversation to continue where you left off.</p></Link><div className="library-actions"><button type="button" onClick={()=>void onConversationPin(chat.id,{pinned:!chat.pinned})}><PushPin weight={chat.pinned?"fill":"bold"}/>{chat.pinned?"Pinned":"Pin"}</button><button type="button" className="danger-text" onClick={()=>void onConversationDelete(chat.id)}><Trash weight="bold"/>Delete</button></div></article>}
 if(type==="file"){const file=item as FileRow,isImage=file.mime_type.startsWith("image/");return <article className="card library-card library-card-file"><CardTop type="File" Icon={TypeIcon}/><button type="button" className="library-file-main" onClick={()=>void onFileDetail(file)}><span className="file-mark"><File weight="fill"/></span><div><h3>{file.name}</h3><p className="library-meta">{Math.max(1,Math.round(file.size_bytes/1024))} KB<span>•</span>{formatDate(file.created_at)}</p><p className="library-excerpt">{file.extraction_status}</p></div></button><div className="library-actions"><button type="button" onClick={()=>void onFavorite("file",file.id,favoriteFiles.includes(file.id))}><PushPin weight={favoriteFiles.includes(file.id)?"fill":"bold"}/>{favoriteFiles.includes(file.id)?"Pinned":"Pin"}</button><button type="button" className="danger-text" onClick={()=>void onFileDelete(file.id,file.name)}><Trash weight="bold"/>Delete</button><Link href={`/chat?file=${file.id}`}>Use in Chat</Link>{crossModalityHandoffs&&isImage&&<Link href={`/images?reference=${encodeURIComponent(file.id)}`}>Edit</Link>}</div></article>}
 const job=item as Job,url=Array.isArray(job.result_urls)?job.result_urls[0]:undefined,studio=type==="image"?"/images":`/${type}`,pinned=favoriteJobs.includes(job.id),title=mediaTitle(job);
 return <article className={`card library-card library-card-${type}`}><CardTop type={type} Icon={TypeIcon}/>{type==="image"&&url&&<button type="button" className="library-thumb image-thumb" onClick={()=>onJobDetail(job)}><img src={url} alt="" loading="lazy"/></button>}{type==="video"&&url&&<button type="button" className="library-thumb video-thumb" onClick={()=>onJobDetail(job)}><video src={url} preload="metadata" muted playsInline/><PlayCircle weight="fill"/></button>}{type==="audio"&&<button type="button" className="library-audio" onClick={()=>onJobDetail(job)}><SpeakerHigh weight="fill"/><span className="audio-wave" aria-hidden="true">||||||||||||||||</span>{url&&<audio src={url} preload="metadata" onClick={event=>event.stopPropagation()}/>}</button>}<button type="button" className="library-card-main library-media-main" onClick={()=>onJobDetail(job)}><h3>{title}</h3><p className="library-meta">{job.model_id}<span>•</span>{formatDate(job.created_at)}</p>{!url&&<p className="library-excerpt">{job.status}</p>}</button><div className="library-actions"><button type="button" onClick={()=>void onFavorite("job",job.id,pinned)}><PushPin weight={pinned?"fill":"bold"}/>{pinned?"Pinned":"Pin"}</button><button type="button" onClick={()=>onJobDetail(job)}>Details</button><Link href={`${studio}?prompt=${encodeURIComponent(job.prompt||"")}`}>Use again</Link>{url&&<a href={url} target="_blank" rel="noreferrer">Open</a>}</div></article>
}

function CardTop({type,Icon}:{type:string;Icon:typeof ChatCircle}){return <div className="library-card-top"><span className={`library-type type-${type.toLowerCase()}`}><Icon weight="fill"/>{type}</span><DotsThree weight="bold" aria-hidden="true"/></div>}

function AssetDetail({detail,loading,crossModalityHandoffs,onClose}:{detail:Detail;loading:boolean;crossModalityHandoffs:boolean;onClose:()=>void}){if(detail.kind==="job"){const item=detail.item,url=Array.isArray(item.result_urls)?item.result_urls[0]:undefined,mime=item.modality,studio=item.modality==="image"?"/images":`/${item.modality}`;return <DetailFrame title={mediaTitle(item)} kicker={`${item.modality} generation`} url={url} mime={mime} loading={false} onClose={onClose} metadata={[["Model",item.model_id],["Status",item.status],["Credits",Number(item.charged_credits||0).toFixed(2)],["Created",new Date(item.created_at).toLocaleString()]]}><Link href={`${studio}?prompt=${encodeURIComponent(item.prompt||"")}`}>Use again</Link>{url&&<a href={url} target="_blank" rel="noreferrer">Open original</a>}</DetailFrame>}const item=detail.item;return <DetailFrame title={item.name} kicker="Library file" url={detail.url} mime={item.mime_type} loading={loading} onClose={onClose} metadata={[["Type",item.mime_type],["Size",`${(item.size_bytes/1024).toFixed(1)} KB`],["Processing",item.extraction_status],["Uploaded",new Date(item.created_at).toLocaleString()]]}><Link href={`/chat?file=${item.id}`}>Use in Chat</Link>{crossModalityHandoffs&&item.mime_type.startsWith("image/")&&<Link href={`/images?reference=${encodeURIComponent(item.id)}`}>Edit in Image</Link>}{detail.url&&<a href={detail.url} target="_blank" rel="noreferrer">Open original</a>}</DetailFrame>}

function DetailFrame({title,kicker,url,mime,loading,onClose,metadata,children}:{title:string;kicker:string;url?:string;mime:string;loading:boolean;onClose:()=>void;metadata:string[][];children:ReactNode}){return <div className="asset-detail-overlay" role="dialog" aria-modal="true" aria-label="Asset details"><button className="workspace-scrim" aria-label="Close asset details" onClick={onClose}/><section className="asset-detail-panel"><header><div><span className="kicker">{kicker}</span><h2>{title}</h2></div><button className="icon-button" onClick={onClose} aria-label="Close"><X weight="bold"/></button></header><div className="asset-detail-scroll"><div className="asset-preview">{loading?<span>Loading secure preview…</span>:url&&(mime==="image"||mime.startsWith("image/"))?<Image src={url} alt="Asset preview" width={1200} height={900} unoptimized/>:url&&(mime==="video"||mime.startsWith("video/"))?<video src={url} controls/>:url&&(mime==="audio"||mime.startsWith("audio/"))?<audio src={url} controls/>:<span>Preview is not available for this asset type.</span>}</div><dl className="asset-metadata">{metadata.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></div><footer>{children}</footer></section></div>}
