"use client";

import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowRight, CaretDown, CaretRight, ChatCircle, ChatTeardropText, CheckCircle, ClockCounterClockwise, CreditCard, DotsThree, DownloadSimple, FolderOpen, GearSix, GridFour, ImageSquare, Lifebuoy, ListBullets, LockKey, NotePencil, PaperPlaneTilt, Plus, ShieldCheck, Star, Trash, User, UserCircle, VideoCamera, Wrench } from "@phosphor-icons/react";
import { PremiumSelect } from "@/components/premium-select";

type Project = { id: string; name: string; instructions?: string | null; updated_at?: string | null };
type FileItem = { id: string; name: string; size_bytes: number; extraction_status: string };
type Settings = { display_name?: string; theme?: string; default_language?: string; default_tier?: string; low_bandwidth?: boolean; daily_spend_limit?: number | null; single_generation_limit?: number | null; custom_instructions?: string };
type Ticket = { id: string; public_id: string; subject: string; status: string; category: string; created_at?: string; updated_at?: string };
type TicketMessage = { id: string; author_role: string; body: string; created_at: string };

export function ProjectsClient() {
  const [projects, setProjects] = useState<Project[]>([]);
  const [name, setName] = useState("");
  const [instructions, setInstructions] = useState("");
  const [status, setStatus] = useState("");
  const [activeProject, setActiveProject] = useState("");
  const [sort, setSort] = useState<"updated" | "name">("updated");
  const [view, setView] = useState<"grid" | "list">("grid");
  const nameInput = useRef<HTMLInputElement>(null);
  async function load() { const r = await fetch("/api/projects"); if (r.ok) setProjects((await r.json()).projects || []); }
  useEffect(() => { const timer = window.setTimeout(() => { setActiveProject(window.localStorage.getItem("amh-active-project") || ""); void load(); }, 0); return () => window.clearTimeout(timer); }, []);
  function activate(id:string){setActiveProject(id);window.localStorage.setItem("amh-active-project",id);window.dispatchEvent(new CustomEvent("amh-project-change",{detail:id}));setStatus(id?"Project activated across every workspace.":"Personal workspace activated.")}
  async function submit(e: FormEvent) {
    e.preventDefault(); setStatus("Creating…");
    const r = await fetch("/api/projects", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, instructions }) });
    const d = await r.json().catch(() => ({})); setStatus(r.ok ? "Project created." : d.error || "Could not create project.");
    if (r.ok) { setName(""); setInstructions(""); await load(); }
  }
  const orderedProjects = useMemo(() => [...projects].sort((a,b) => sort === "name" ? a.name.localeCompare(b.name) : String(b.updated_at || "").localeCompare(String(a.updated_at || ""))), [projects, sort]);
  const instructionCount = projects.filter((project) => project.instructions?.trim()).length;
  const updated = (value?: string | null) => value ? new Date(value).toLocaleDateString(undefined, { month:"short", day:"numeric" }) : "Recently";
  const edit = async (project: Project) => { const next = prompt("Update project instructions:", project.instructions || ""); if(next === null) return; await fetch(`/api/projects/${project.id}`, { method:"PATCH", headers:{"Content-Type":"application/json"}, body:JSON.stringify({instructions:next}) }); await load(); };
  const remove = async (project: Project) => { if(!confirm("Delete this project? Chats will remain but will no longer belong to it.")) return; await fetch(`/api/projects/${project.id}`, {method:"DELETE"}); if(activeProject===project.id) activate(""); await load(); };
  return <div className="projects-redesign">
    <header className="projects-hero"><div className="projects-hero-copy"><span className="projects-hero-icon"><FolderOpen weight="fill" /></span><div><span className="kicker">Workspace</span><h1>Projects</h1><p>Keep instructions, conversations, and selected knowledge together for focused work.</p></div></div><div className="projects-hero-art"><span>Turn ideas into<br/>lasting workspaces.</span><i><FolderOpen weight="fill" /></i></div></header>
    <section className="projects-stats" aria-label="Project summary"><div><FolderOpen weight="duotone"/><strong>{projects.length}</strong><span>Total projects<small>Keep your ideas organized</small></span></div><div><NotePencil weight="duotone"/><strong>{instructionCount}</strong><span>Saved instructions<small>Reusable project context</small></span></div><div><CheckCircle weight="duotone"/><strong>{activeProject ? 1 : 0}</strong><span>Active workspace<small>{activeProject ? "Project connected" : "Personal workspace"}</small></span></div></section>
    <div className="projects-workspace">
      <section className="projects-create-panel"><div className="kicker">New project</div><h2>Build a persistent workspace</h2><p>Instructions and assets remain available while you move between specialist studios.</p><form onSubmit={submit} className="form-stack"><label className="label">Project name<input ref={nameInput} className="input" value={name} onChange={(e) => setName(e.target.value)} placeholder="E.g. Brand Campaign, Product Research…" required /></label><label className="label">Project instructions<textarea className="textarea" value={instructions} onChange={(e) => setInstructions(e.target.value)} placeholder="Brand voice, goals, constraints, client context…" maxLength={10000}/><small className="projects-character-count">{instructions.length}/10,000</small></label><button className="projects-create-button" disabled={!name.trim()}><span>Create project</span><ArrowRight weight="bold" /></button>{status && <div className="small muted" role="status">{status}</div>}</form></section>
      <section className="projects-list-panel"><div className="projects-list-head"><div><div className="kicker">Your projects</div><h2>Continue creating</h2></div><div className="projects-toolbar"><label className="projects-sort">Sort <select value={sort} onChange={(event)=>setSort(event.target.value as "updated" | "name")} aria-label="Sort projects"><option value="updated">Last updated</option><option value="name">Name</option></select><CaretDown weight="bold" /></label><div className="projects-view" aria-label="Project view"><button className={view === "grid" ? "active" : ""} type="button" onClick={()=>setView("grid")} aria-label="Grid view"><GridFour weight="bold"/></button><button className={view === "list" ? "active" : ""} type="button" onClick={()=>setView("list")} aria-label="List view"><ListBullets weight="bold"/></button></div></div></div>
        <div className={`project-card-grid ${view === "list" ? "is-list" : ""}`}>{orderedProjects.length ? orderedProjects.map((project, index) => <article className={`project-card ${activeProject===project.id?"active":""}`} key={project.id}><div className="project-card-top"><span className={`project-card-icon tone-${index % 3}`}><FolderOpen weight="fill" /></span><div className="project-card-state">{activeProject===project.id ? <><i/>Active</> : "Project"}</div><button type="button" className="project-more" onClick={()=>edit(project)} aria-label={`Edit ${project.name}`}><DotsThree weight="bold"/></button></div><h3 title={project.name}>{project.name}</h3><p>{project.instructions || "No saved instructions yet. Add a brief to guide work across your studios."}</p><div className="project-meta"><span><NotePencil/> {project.instructions?.trim() ? "Instructions saved" : "No instructions"}</span><span>◷ Updated {updated(project.updated_at)}</span></div><div className="project-actions"><a className="project-primary-action" href={`/chat?project=${project.id}`}><ChatCircle weight="fill"/>Open Chat</a><a href="/images"><ImageSquare/>Image</a><a href="/video"><VideoCamera/>Video</a></div><div className="project-secondary-actions"><button type="button" onClick={()=>activate(project.id)}><Star weight="bold"/>{activeProject===project.id ? "Active" : "Set active"}</button><button type="button" onClick={()=>edit(project)}><NotePencil weight="bold"/>Edit</button><button type="button" className="danger" onClick={()=>remove(project)}><Trash weight="bold"/>Delete</button></div></article>) : <div className="projects-empty"><FolderOpen weight="duotone"/><h3>Create your first project</h3><p>Keep chats and generation context together in one focused workspace.</p><button type="button" onClick={()=>nameInput.current?.focus()}><Plus weight="bold"/>Create project</button></div>}<button type="button" className="projects-add-card" onClick={()=>nameInput.current?.focus()}><span><Plus weight="bold"/></span><strong>Create another project</strong><small>Keep building. Turn ideas into organized workspaces.</small></button></div>
      </section>
    </div>
  </div>;
}

export function FilesClient() {
  const [files, setFiles] = useState<FileItem[]>([]), [projects, setProjects] = useState<Project[]>([]);
  const [file, setFile] = useState<File | null>(null), [projectId, setProjectId] = useState(""), [status, setStatus] = useState("");
  async function load() { const [fr, pr] = await Promise.all([fetch("/api/files"), fetch("/api/projects")]); if (fr.ok) setFiles((await fr.json()).files || []); if (pr.ok) setProjects((await pr.json()).projects || []); }
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, []);
  async function upload(e: FormEvent) {
    e.preventDefault(); if (!file) return; const fd = new FormData(); fd.append("file", file); if (projectId) fd.append("projectId", projectId); setStatus("Uploading and preparing context…");
    const r = await fetch("/api/files", { method: "POST", body: fd }); const d = await r.json().catch(() => ({})); setStatus(r.ok ? "Uploaded successfully." : d.error || "Upload failed.");
    if (r.ok) { setFile(null); await load(); }
  }
  async function remove(id: string) { if (!confirm("Delete this file?")) return; await fetch(`/api/files/${id}`, { method: "DELETE" }); await load(); }
  return <div className="studio-layout"><section className="card studio-panel"><div className="kicker">Files</div><h2>Upload knowledge</h2><p className="muted small">PDF, DOCX, TXT, Markdown, CSV, common code files and images. Up to 50 MB. Supported documents are extracted privately for AI context.</p><form onSubmit={upload} className="form-stack"><input className="input" type="file" onChange={(e) => setFile(e.target.files?.[0] || null)} required /><label className="label">Project (optional)<PremiumSelect value={projectId} onChange={setProjectId} options={[{value:"",label:"General library"}, ...projects.map((p) => ({value:p.id,label:p.name}))]} /></label><button className="btn btn-primary">Upload file</button>{status && <div className="small muted">{status}</div>}</form></section><section className="card studio-panel"><div className="kicker">Private library</div><div className="stack-list">{files.length ? files.map((f) => <div className="soft-card list-pad" key={f.id}><div className="row-between"><b>{f.name}</b><button className="icon-button danger-text" onClick={() => remove(f.id)}>Delete</button></div><div className="muted small">{Math.max(1, Math.round(Number(f.size_bytes) / 1024))} KB · {f.extraction_status === "ready" ? "AI context ready" : f.extraction_status}</div></div>) : <div className="muted">No files uploaded yet.</div>}</div></section></div>;
}

export function SettingsClient({ initial }: { initial: Settings }) {
  const router = useRouter();
  const [state, setState] = useState({ displayName: initial.display_name || "", theme: initial.theme || "system", defaultLanguage: initial.default_language || "auto", defaultTier: initial.default_tier || "auto", lowBandwidth: Boolean(initial.low_bandwidth), dailySpendLimit: initial.daily_spend_limit ?? "", singleGenerationLimit: initial.single_generation_limit ?? "", customInstructions: initial.custom_instructions || "" });
  const [status, setStatus] = useState(""); const [deleteText, setDeleteText] = useState("");
  async function save(e: FormEvent) { e.preventDefault(); const payload = { ...state, dailySpendLimit: state.dailySpendLimit === "" ? null : Number(state.dailySpendLimit), singleGenerationLimit: state.singleGenerationLimit === "" ? null : Number(state.singleGenerationLimit) }; const r = await fetch("/api/settings", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const d = await r.json().catch(() => ({})); setStatus(r.ok ? "Settings saved." : d.error || "Could not save settings."); if (r.ok && state.theme !== "system") { localStorage.setItem("amh-theme", state.theme); document.documentElement.dataset.theme = state.theme; } }
  async function deleteAccount() { if (deleteText !== "DELETE MY ACCOUNT") return; if (!confirm("This permanently deletes your account and associated data. Continue?")) return; const r = await fetch("/api/account/delete", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ confirmation: deleteText }) }); if (r.ok) router.push("/"); else setStatus((await r.json()).error || "Account deletion failed."); }
  return <div className="settings-grid">
    <form className="card studio-panel settings-profile-panel form-stack" onSubmit={save}>
      <div className="settings-panel-heading"><span><UserCircle weight="fill" /></span><div><div className="kicker">Profile &amp; AI defaults</div><p>Set up your profile and default preferences for a personalized experience.</p></div></div>
      <label className="label">Display name<input className="input" value={state.displayName} onChange={(e) => setState({ ...state, displayName: e.target.value })} /></label>
      <div className="two-col"><label className="label">Theme<PremiumSelect value={state.theme} onChange={(value) => setState({ ...state, theme: value })} options={[{ value: "system", label: "System" }, { value: "dark", label: "Dark" }, { value: "light", label: "Light" }]} /></label><label className="label">Default AI tier<PremiumSelect value={state.defaultTier} onChange={(value) => setState({ ...state, defaultTier: value })} options={[{ value: "auto", label: "Auto Best" }, { value: "budget", label: "Budget" }, { value: "balanced", label: "Balanced" }, { value: "premium", label: "Premium" }, { value: "flagship", label: "Flagship" }]} /></label></div>
      <label className="label">Default language<PremiumSelect value={state.defaultLanguage} onChange={(value) => setState({ ...state, defaultLanguage: value })} options={[{ value: "auto", label: "Auto detect" }, { value: "en", label: "English" }, { value: "ur", label: "Urdu" }, { value: "roman-ur", label: "Roman Urdu" }]} /></label>
      <label className="label">Custom instructions<textarea className="textarea" value={state.customInstructions} onChange={(e) => setState({ ...state, customInstructions: e.target.value })} placeholder="How should All Model Hub respond to you?" maxLength={1000} /><small className="settings-count">{state.customInstructions.length}/1000</small></label>
      <label className="check-row settings-bandwidth"><input type="checkbox" checked={state.lowBandwidth} onChange={(e) => setState({ ...state, lowBandwidth: e.target.checked })} /><span><b>Low-bandwidth mode</b><small>Use less data for slower connections. May reduce quality or speed.</small></span></label>
      <div className="two-col"><label className="label">Daily spend limit<input className="input" type="number" min={1} value={state.dailySpendLimit} onChange={(e) => setState({ ...state, dailySpendLimit: e.target.value })} placeholder="Optional Credits" /><small>Maximum credits to spend per day.</small></label><label className="label">Single generation limit<input className="input" type="number" min={1} value={state.singleGenerationLimit} onChange={(e) => setState({ ...state, singleGenerationLimit: e.target.value })} placeholder="Optional Credits" /><small>Maximum credits per individual generation.</small></label></div>
      <button className="btn btn-primary settings-save"><GearSix weight="bold" />Save settings</button>{status && <div className="small muted" role="status">{status}</div>}
    </form>
    <aside className="settings-side-stack">
      <section className="card studio-panel settings-privacy-panel"><div className="settings-panel-heading"><span><ShieldCheck weight="fill" /></span><div><div className="kicker">Privacy &amp; account</div><p>Your data, privacy, and account controls.</p></div></div><div className="settings-data-card"><span><LockKey weight="fill" /></span><div><h2>Your data, your control.</h2><p>Export your account data or permanently remove your account. Private chats are not saved in normal chat history.</p></div><a className="btn btn-ghost settings-export" href="/api/account/export"><DownloadSimple weight="bold" />Download my data</a></div><div className="danger-zone settings-delete-zone"><div><span><Trash weight="fill" /></span><b>Delete account</b><small>This action cannot be undone.</small></div><p>Type DELETE MY ACCOUNT to enable permanent deletion.</p><input className="input" value={deleteText} onChange={(e) => setDeleteText(e.target.value)} placeholder="DELETE MY ACCOUNT" /><button type="button" className="btn btn-danger" disabled={deleteText !== "DELETE MY ACCOUNT"} onClick={deleteAccount}><Trash weight="bold" />Delete account permanently</button></div></section>
      <section className="card studio-panel settings-protection-card"><span><ShieldCheck weight="fill" /></span><div><b>Secure by design</b><small>Your privacy matters.</small><p>Your data is encrypted in transit and at rest. We follow industry best practices to keep your information safe.</p></div><i>Protected</i></section>
    </aside>
  </div>;
}

export function SupportClient() {
  const [tickets, setTickets] = useState<Ticket[]>([]), [active, setActive] = useState<Ticket | null>(null), [thread, setThread] = useState<TicketMessage[]>([]);
  const [category, setCategory] = useState("technical"), [subject, setSubject] = useState(""), [message, setMessage] = useState(""), [reply, setReply] = useState(""), [status, setStatus] = useState(""), [submitting, setSubmitting] = useState(false), [sending, setSending] = useState(false);
  async function load() { const r = await fetch("/api/support"); if (r.ok) setTickets((await r.json()).tickets || []); }
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, []);
  async function open(ticket: Ticket) { setActive(ticket); setThread([]); const r = await fetch(`/api/support/${ticket.id}`); if (r.ok) setThread((await r.json()).messages || []); else setStatus("Could not load this conversation."); }
  async function submit(e: FormEvent) { e.preventDefault(); if (submitting) return; setSubmitting(true); const r = await fetch("/api/support", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ category, subject, message }) }); const d = await r.json().catch(() => ({})); setStatus(r.ok ? `Created ${d.ticket.public_id}` : d.error || "Ticket failed."); if (r.ok) { setSubject(""); setMessage(""); await load(); await open(d.ticket); } setSubmitting(false); }
  async function sendReply(e: FormEvent) { e.preventDefault(); if (!active || !reply.trim() || sending) return; setSending(true); const r = await fetch(`/api/support/${active.id}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message: reply }) }); if (r.ok) { setReply(""); await open(active); } else setStatus("Could not send reply."); setSending(false); }
  const categoryOptions = [{ value: "payment", label: "Payment" }, { value: "wallet", label: "Wallet" }, { value: "generation", label: "Generation" }, { value: "account", label: "Account" }, { value: "technical", label: "Technical" }, { value: "refund", label: "Refund" }, { value: "other", label: "Other" }];
  const categoryIcon = (value: string) => value === "account" ? <User weight="bold" /> : value === "payment" || value === "wallet" || value === "refund" ? <CreditCard weight="bold" /> : value === "technical" ? <Wrench weight="bold" /> : <ChatTeardropText weight="bold" />;
  const prettyDate = (value?: string) => value ? new Intl.DateTimeFormat(undefined, { month: "short", day: "numeric" }).format(new Date(value)) : "Recently";
  const statusClass = (value: string) => value.toLowerCase().replace(/\s+/g, "-");
  return <div className="support-workspace">
    <div className="support-shortcuts" aria-label="Support topics"><button type="button" onClick={() => setCategory("technical")}>{categoryIcon("technical")}<span><b>Technical</b><small>Get help with errors</small></span></button><button type="button" onClick={() => setCategory("payment")}>{categoryIcon("payment")}<span><b>Billing</b><small>Payments &amp; credits</small></span></button><button type="button" onClick={() => setCategory("account")}>{categoryIcon("account")}<span><b>Account</b><small>Profile &amp; settings</small></span></button></div>
    <div className="support-layout"><div className="support-left-column">
      <form className="card studio-panel support-ticket-form form-stack" onSubmit={submit}><div className="support-panel-heading"><span><Plus weight="bold" /></span><div><h2>New ticket</h2><p>Send us a message and our team will get back to you as soon as possible.</p></div></div><label className="label">Category<PremiumSelect value={category} onChange={setCategory} options={categoryOptions} /></label><label className="label">Subject<input className="input" value={subject} onChange={(e) => setSubject(e.target.value)} placeholder="Briefly describe your issue…" required maxLength={120} /></label><label className="label support-message-label">Message<textarea className="textarea" value={message} onChange={(e) => setMessage(e.target.value)} placeholder="Tell us more about your issue. Include any relevant details, steps to reproduce, or error messages…" required minLength={10} maxLength={5000} /><small>{message.length}/5000</small></label><div className="support-routing-note"><Lifebuoy weight="fill" /><span><b>Direct support routing</b><small>Your selected category helps us send this to the right team.</small></span></div><button className="btn btn-primary support-create" disabled={submitting}><PaperPlaneTilt weight="fill" />{submitting ? "Creating ticket…" : "Create ticket"}</button>{status && <div className="small muted" role="status">{status}</div>}</form>
      <section className="card studio-panel support-tickets-panel"><div className="support-panel-heading"><span><ClockCounterClockwise weight="fill" /></span><div><h2>Your tickets</h2><p>View and manage your support tickets.</p></div><button type="button" onClick={() => void load()}>Refresh</button></div><div className="support-ticket-list">{tickets.length ? tickets.map((ticket) => <button className={`support-ticket-row ${active?.id === ticket.id ? "active" : ""}`} onClick={() => void open(ticket)} key={ticket.id}><span className="support-ticket-icon">{categoryIcon(ticket.category)}</span><span className="support-ticket-copy"><b>{ticket.subject}</b><small>{ticket.public_id} · {ticket.category}</small></span><span className={`support-status ${statusClass(ticket.status)}`}><i />{ticket.status}</span><time>{prettyDate(ticket.updated_at || ticket.created_at)}</time><CaretRight weight="bold" /></button>) : <div className="support-empty-tickets"><Lifebuoy weight="duotone" /><b>No support tickets yet</b><span>Use the form above whenever you need a hand.</span></div>}</div></section>
    </div>
    <section className="card studio-panel support-conversation"><header className="support-conversation-head"><span><ChatCircle weight="fill" /></span><div><h2>Conversation</h2><p>{active ? active.public_id : "Select a ticket to view the full support thread."}</p></div>{active && <i className={`support-status ${statusClass(active.status)}`}><b />{active.status}</i>}</header>{active ? <><div className="support-thread">{thread.length ? thread.map((entry) => <article className={`support-thread-message ${entry.author_role === "user" ? "user" : "support"}`} key={entry.id}><span className="support-message-avatar">{entry.author_role === "user" ? "A" : <Lifebuoy weight="fill" />}</span><div><header><b>{entry.author_role === "user" ? "You" : "All Model Hub Support"}</b><time>{new Date(entry.created_at).toLocaleString()}</time><DotsThree weight="bold" /></header><p>{entry.body}</p></div></article>) : <div className="support-thread-loading">Loading conversation…</div>}</div><form onSubmit={sendReply} className="support-reply-form"><textarea className="textarea" value={reply} onChange={(e) => setReply(e.target.value)} placeholder="Write a reply…" maxLength={5000} /><button className="btn btn-primary" disabled={!reply.trim() || sending}><PaperPlaneTilt weight="fill" />{sending ? "Sending…" : "Send reply"}</button></form></> : <div className="support-conversation-empty"><ChatCircle weight="duotone" /><b>Your conversation will appear here</b><span>Select a ticket to read the full support thread and reply.</span></div>}</section>
    </div>
  </div>;
}

