"use client";

import Image from "next/image";
import React, { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, ArrowRight, Check, CheckCircle, Clock, Copy, CreditCard, FileArrowUp, Receipt, ShieldCheck, Sparkle, UploadSimple, Wallet } from "@phosphor-icons/react";
import { calculateTopupBonus, getNextTopupTier, isValidTopupAmount, TOPUP_BONUS_TIERS, TOPUP_MAX_PKR, TOPUP_MIN_PKR } from "@/lib/topup-bonus";

type Method = { id: string; label: string; accountTitle: string; accountNumber: string; iban?: string; instructions: string };
type WalletData = { available: number; purchased: number; promo: number; reserved: number };
type Transaction = { id: string; created_at: string; type: string; amount: number; balance_after?: number | null; reference_id?: string | null };
type SubmittedPayment = { public_id: string; amount_pkr: number; bonus_credits: number; total_credits: number };
const suggested = [500, 1000, 2500, 5000, 10000];
const methodMeta: Record<string, { caption: string; logo: string }> = { easypaisa: { caption: "Mobile wallet", logo: "/payment-logos/easypaisa.svg" }, meezan: { caption: "Bank transfer", logo: "/payment-logos/meezan-bank.svg" } };
const money = (value: number) => Math.max(0, value).toLocaleString("en-PK", { maximumFractionDigits: 2 });

export function WalletClient({ initialWallet, initialTransactions }: { initialWallet: WalletData; initialTransactions: Transaction[] }) {
  const [wallet, setWallet] = useState(initialWallet), [transactions, setTransactions] = useState(initialTransactions), [methods, setMethods] = useState<Method[]>([]);
  const [method, setMethod] = useState("easypaisa"), [amountText, setAmountText] = useState("1000"), [reference, setReference] = useState(""), [proof, setProof] = useState<File | null>(null);
  const [status, setStatus] = useState(""), [busy, setBusy] = useState(false), [copied, setCopied] = useState(""), [step, setStep] = useState<1 | 2 | 3>(1);
  const [direction, setDirection] = useState<"forward" | "back">("forward"), [submitted, setSubmitted] = useState<SubmittedPayment | null>(null);
  const fileRef = useRef<HTMLInputElement>(null), panelRef = useRef<HTMLDivElement>(null);
  useEffect(() => { fetch("/api/payments/manual").then(r => r.json()).then(d => { setMethods(d.methods || []); setMethod(current => d.methods?.some((x: Method) => x.id === current) ? current : d.methods?.[0]?.id || current); }).catch(() => setStatus("Payment methods are temporarily unavailable. Please try again.")); }, []);
  const amount = Number(amountText), selected = methods.find(x => x.id === method), bonus = useMemo(() => calculateTopupBonus(amount), [amount]);
  const amountError = amountText !== "" && (!Number.isInteger(amount) || amount < TOPUP_MIN_PKR ? `Minimum top-up is PKR ${money(TOPUP_MIN_PKR)}` : amount > TOPUP_MAX_PKR ? `Maximum top-up is PKR ${money(TOPUP_MAX_PKR)}` : "");
  const canContinue = isValidTopupAmount(amount) && Boolean(selected);
  function moveTo(next: 1 | 2 | 3) { if (next > 1 && !canContinue) return setStatus(amountError || "Choose an amount and payment method first."); setDirection(next >= step ? "forward" : "back"); setStatus(""); setStep(next); window.setTimeout(() => panelRef.current?.focus(), 40); }
  function updateAmount(value: string) { setAmountText(value.replace(/\D/g, "").slice(0, 6)); setStatus(""); }
  function chooseProof(file: File | null) { if (!file) return setProof(null); const allowed = ["image/jpeg", "image/png", "image/webp", "application/pdf"]; if (!allowed.includes(file.type)) { setProof(null); if (fileRef.current) fileRef.current.value = ""; return setStatus("Use a JPG, PNG, WebP or PDF receipt."); } if (file.size > 5 * 1024 * 1024) { setProof(null); if (fileRef.current) fileRef.current.value = ""; return setStatus("Receipt must be 5 MB or smaller."); } setProof(file); setStatus(""); }
  async function copyValue(value: string, key: string) { try { await navigator.clipboard.writeText(value); setCopied(key); window.setTimeout(() => setCopied(""), 1600); } catch { setStatus("Copy was blocked. Select the detail and copy it manually."); } }
  async function refresh() { const r = await fetch("/api/wallet"); if (r.ok) { const d = await r.json(); setWallet(d.wallet); setTransactions(d.transactions || []); } }
  async function submit(event: FormEvent) {
    event.preventDefault();
    if (!isValidTopupAmount(amount)) return setStatus(amountError || "Enter a valid top-up amount.");
    if (reference.trim().length < 4) return setStatus("Enter a valid transaction/reference ID.");
    if (!proof) return setStatus("Add your payment receipt before submitting.");
    setBusy(true); setStatus("");
    const form = new FormData(); form.append("method", method); form.append("amount", String(amount)); form.append("transactionReference", reference.trim()); form.append("proof", proof);
    const r = await fetch("/api/payments/manual", { method: "POST", body: form }), d = await r.json().catch(() => ({})); setBusy(false);
    if (!r.ok) return setStatus(d.error || "Could not submit payment.");
    setSubmitted({ public_id: d.payment.public_id, amount_pkr: Number(d.payment.amount_pkr), bonus_credits: Number(d.payment.bonus_credits), total_credits: Number(d.payment.total_credits) }); await refresh();
  }
  function reset() { setSubmitted(null); setStep(1); setReference(""); setProof(null); setStatus(""); if (fileRef.current) fileRef.current.value = ""; }
  const cards = [{ label: "Available", value: wallet.available, detail: "Ready to use", icon: CreditCard, primary: true }, { label: "Purchased", value: wallet.purchased, detail: "Never expires", icon: CheckCircle }, { label: "Promotional", value: wallet.promo, detail: "Tracked separately", icon: Receipt }, { label: "Reserved", value: wallet.reserved, detail: "Held for active jobs", icon: Clock }];
  return <div className="wallet-workspace">
    <section className="wallet-balance-grid" aria-label="Wallet balances">{cards.map(c => { const Icon = c.icon; return <div className={`card wallet-balance-card ${c.primary ? "is-primary" : ""}`} key={c.label}><span className="wallet-balance-icon"><Icon weight="fill" /></span><span className="wallet-balance-label">{c.label}</span><strong>{Number(c.value).toFixed(2)}</strong><small>{c.detail}</small></div>; })}</section>
    <section className="wallet-topup-shell"><header className="wallet-topup-head"><div><span className="kicker">Add credits</span><h2>Top up. Get more AI power.</h2><p>One credit equals PKR 1. Unlock up to 20% bonus credits.</p></div><span className="wallet-review-badge"><Clock weight="fill" />Manual review</span></header>
      {!submitted && <div className="wallet-steps" aria-label={`Payment step ${step} of 3`}>{["Amount", "Payment", "Proof"].map((label, index) => { const number = index + 1; return <button type="button" key={label} className={number === step ? "is-current" : number < step ? "is-complete" : ""} onClick={() => number < step && moveTo(number as 1 | 2 | 3)} disabled={number > step}><b>{number < step ? <Check weight="bold" /> : number}</b><i>{label}</i></button>; })}</div>}
      {submitted ? <SuccessState payment={submitted} reset={reset} /> : <form onSubmit={submit}><div ref={panelRef} tabIndex={-1} className={`wallet-wizard-panel is-${direction}`} key={step}>
        {step === 1 && <section className="wallet-step-layout"><div className="wallet-step-main"><StepHeading number="01" title="Choose your top-up" detail="Add PKR 500–100,000. Bigger top-ups unlock bigger bonus credits." /><label className="label">How much would you like to add?<span className={`wallet-amount-field ${amountError ? "has-error" : ""}`}><span>PKR</span><input inputMode="numeric" min={TOPUP_MIN_PKR} max={TOPUP_MAX_PKR} value={amountText} onChange={e => updateAmount(e.target.value)} aria-invalid={Boolean(amountError)} aria-describedby="amount-help" /><small>{bonus.percent}% bonus</small></span></label>{amountError && <p id="amount-help" className="wallet-field-error" role="alert">{amountError}</p>}<div className="wallet-amount-chips">{suggested.map(v => <button type="button" className={amount === v ? "active" : ""} onClick={() => setAmountText(String(v))} key={v}>PKR {money(v)}</button>)}</div><BonusLadder amount={amount} /></div>
          <aside className="wallet-step-side"><ValueSummary amount={amount} bonus={bonus.bonusCredits} total={bonus.totalCredits} /><h3>How would you like to pay?</h3><div className="wallet-method-grid" role="radiogroup">{methods.map(item => <button type="button" role="radio" aria-checked={method === item.id} className={`wallet-method ${method === item.id ? "active" : ""}`} onClick={() => setMethod(item.id)} key={item.id}><PaymentLogo method={item.id} /><span><strong>{item.label}</strong><small>{methodMeta[item.id]?.caption || "Bank transfer"}</small></span>{method === item.id && <Check weight="bold" />}</button>)}</div>{!methods.length && <div className="wallet-account-loading">Loading secure payment methods…</div>}<button type="button" className="btn btn-primary wallet-submit" disabled={!canContinue} onClick={() => moveTo(2)}>Continue to payment <ArrowRight weight="bold" /></button><p className="wallet-submit-help">You’ll receive {money(bonus.totalCredits)} Credits after approval.</p></aside></section>}
        {step === 2 && <section className="wallet-step-layout"><div className="wallet-step-main"><StepHeading number="02" title="Make your payment" detail="Transfer the exact amount using the payment method you selected." /><div className="wallet-pay-focus"><small>Send exactly</small><strong>PKR {money(amount)}</strong><p>Your +{money(bonus.bonusCredits)} bonus is added by All Model Hub after verification.</p></div><div className="wallet-trust-strip"><ShieldCheck weight="fill" /><span><b>Verified payment details</b><small>Your credits are added after payment verification.</small></span></div></div><aside className="wallet-step-side"><div className="wallet-transfer-brand"><PaymentLogo method={method} /><div><small>Transfer via</small><strong>{selected?.label}</strong></div><span className="wallet-secure"><ShieldCheck weight="fill" />Verified</span></div>{selected ? <div className="wallet-account-details"><CopyRow label="Account title" value={selected.accountTitle} id="title" copied={copied} copyValue={copyValue} /><CopyRow label={selected.iban ? "Account number" : "Mobile account"} value={selected.accountNumber} id="account" copied={copied} copyValue={copyValue} />{selected.iban && <CopyRow label="IBAN" value={selected.iban} id="iban" copied={copied} copyValue={copyValue} />}</div> : <div className="wallet-account-loading">Loading secure payment details…</div>}<CompactSummary amount={amount} bonus={bonus.bonusCredits} total={bonus.totalCredits} method={selected?.label || method} /><div className="wallet-actions"><button type="button" className="btn btn-ghost" onClick={() => moveTo(1)}><ArrowLeft />Back</button><button type="button" className="btn btn-primary" onClick={() => moveTo(3)}>I’ve made the transfer <ArrowRight /></button></div></aside></section>}
        {step === 3 && <section className="wallet-step-layout"><div className="wallet-step-main"><StepHeading number="03" title="Confirm your transfer" detail="Add your transaction ID and payment receipt." /><label className="label">Transaction / reference ID<input className="input" value={reference} onChange={e => setReference(e.target.value)} required minLength={4} maxLength={120} disabled={busy} placeholder="e.g. 12345678901" /></label><input ref={fileRef} className="wallet-file-native" id="wallet-proof" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={e => chooseProof(e.target.files?.[0] || null)} required disabled={busy} /><label className={`wallet-proof-drop ${proof ? "has-file" : ""}`} htmlFor="wallet-proof"><span>{proof ? <CheckCircle weight="fill" /> : <FileArrowUp weight="duotone" />}</span><div><strong>{proof ? "Receipt attached" : "Upload payment receipt"}</strong><small>{proof ? proof.name : "JPG, PNG, WebP or PDF · max 5 MB"}</small></div><b>{proof ? "Change" : "Browse"}</b></label></div><aside className="wallet-step-side"><CompactSummary amount={amount} bonus={bonus.bonusCredits} total={bonus.totalCredits} method={selected?.label || method} /><button className="btn btn-primary wallet-submit" disabled={busy || !proof || reference.trim().length < 4}><UploadSimple weight="bold" />{busy ? "Submitting securely…" : "Submit payment for verification"}</button><p className="wallet-submit-help"><ShieldCheck weight="fill" />Your payment will be reviewed before credits are added.</p><button type="button" className="wallet-back-link" disabled={busy} onClick={() => moveTo(2)}><ArrowLeft />Back to payment details</button></aside></section>}
      </div>{status && <div className="wallet-status" role="alert" aria-live="polite">{status}</div>}</form>}
    </section>
    <section className="wallet-protection-strip"><div><ShieldCheck weight="fill" /><span><b>Credits never expire</b><small>Your purchased balance stays yours.</small></span></div><div><Wallet weight="fill" /><span><b>Protected spending</b><small>Reservations prevent a negative balance.</small></span></div><div><Receipt weight="fill" /><span><b>Clear ledger</b><small>Every movement is recorded below.</small></span></div></section>
    <section className="wallet-ledger"><div className="wallet-ledger-heading"><span><Receipt weight="fill" /><span><span className="kicker">Receipts</span><h2 className="page-title">Recent transactions</h2></span></span><small>Every movement is recorded</small></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Type</th><th>Amount</th><th>Balance after</th><th>Reference</th></tr></thead><tbody>{transactions.length ? transactions.map(t => <tr key={t.id}><td>{new Date(t.created_at).toLocaleString()}</td><td>{t.type}</td><td style={{ color: Number(t.amount) >= 0 ? "var(--success)" : "var(--text)" }}>{Number(t.amount) >= 0 ? "+" : ""}{Number(t.amount).toFixed(4)}</td><td>{t.balance_after == null ? "—" : Number(t.balance_after).toFixed(4)}</td><td>{t.reference_id || "—"}</td></tr>) : <tr><td colSpan={5} className="muted">No transactions yet.</td></tr>}</tbody></table></div></section>
  </div>;
}

function PaymentLogo({ method }: { method: string }) { const meta = methodMeta[method] || methodMeta.easypaisa; return <span className="wallet-method-logo"><Image src={meta.logo} alt={`${method === "meezan" ? "Meezan Bank" : "Easypaisa"} logo`} width={50} height={50} sizes="50px" /></span>; }
function StepHeading({ number, title, detail }: { number: string; title: string; detail: string }) { return <div className="wallet-form-title"><span>{number}</span><div><h3>{title}</h3><p>{detail}</p></div></div>; }
function ValueSummary({ amount, bonus, total }: { amount: number; bonus: number; total: number }) { return <div className="wallet-value-summary"><span><small>You pay</small><b>PKR {money(amount)}</b></span><span className="bonus"><small>Bonus</small><b>+{money(bonus)}</b></span><span className="total"><small>You receive</small><strong key={total}>{money(total)} Credits</strong></span></div>; }
function CompactSummary({ amount, bonus, total, method }: { amount: number; bonus: number; total: number; method: string }) { return <div className="wallet-compact-summary"><span><small>Payment</small><b>PKR {money(amount)}</b></span><span><small>Bonus locked</small><b className="bonus">+{money(bonus)}</b></span><span><small>Total after approval</small><b>{money(total)} Credits</b></span><span><small>Via</small><b>{method}</b></span></div>; }
function BonusLadder({ amount }: { amount: number }) { const next = getNextTopupTier(amount); return <div className="wallet-bonus-ladder"><div><b>More value as you top up</b><span>{next ? `Add PKR ${money(next.remaining)} more to unlock ${next.percent}% bonus` : "Maximum bonus unlocked — 20%"}</span></div><div className="wallet-tier-track">{TOPUP_BONUS_TIERS.map(tier => <span className={amount >= tier.minimum ? "unlocked" : ""} key={tier.minimum}><small>{money(tier.minimum)}{tier.minimum === 10000 ? "+" : ""}</small><b>+{tier.percent}%</b>{tier.badge && <em>{tier.badge}</em>}</span>)}</div></div>; }
function CopyRow({ label, value, id, copied, copyValue }: { label: string; value: string; id: string; copied: string; copyValue: (value: string, key: string) => void }) { return <div className={`wallet-copy-row ${copied === id ? "is-copied" : ""}`}><span><small>{label}</small><strong>{value}</strong></span><button type="button" onClick={() => copyValue(value, id)}>{copied === id ? <Check weight="bold" /> : <Copy weight="bold" />}{copied === id ? "Copied" : "Copy"}</button></div>; }
function SuccessState({ payment, reset }: { payment: SubmittedPayment; reset: () => void }) { return <div className="wallet-success" aria-live="polite"><span className="wallet-success-icon"><Check weight="bold" /><Sparkle weight="fill" /></span><span className="kicker">Submitted securely</span><h3>Payment submitted</h3><p><b>{payment.public_id}</b> is now waiting for verification.</p><div className="wallet-compact-summary"><span><small>Payment</small><b>PKR {money(payment.amount_pkr)}</b></span><span><small>Bonus locked</small><b className="bonus">+{money(payment.bonus_credits)} Credits</b></span><span><small>You’ll receive after approval</small><b>{money(payment.total_credits)} Credits</b></span></div><div className="wallet-status-track"><span className="done"><Check />Submitted</span><i /><span>Under review</span><i /><span>Credits added</span></div><button type="button" className="btn btn-primary" onClick={reset}>Make another top-up</button></div>; }

