"use client";
import React,{FormEvent,useEffect,useRef,useState} from "react";
import {Check,CheckCircle,Clock,Copy,CreditCard,FileArrowUp,Info,Receipt,ShieldCheck,UploadSimple,Wallet} from "@phosphor-icons/react";
type Method={id:string;label:string;accountTitle:string;accountNumber:string;iban?:string;instructions:string};type WalletData={available:number;purchased:number;promo:number;reserved:number};type Transaction={id:string;created_at:string;type:string;amount:number;balance_after?:number|null;reference_id?:string|null};
const suggested=[500,1000,2500,5000];
export function WalletClient({initialWallet,initialTransactions}:{initialWallet:WalletData;initialTransactions:Transaction[]}){
 const[wallet,setWallet]=useState(initialWallet),[transactions,setTransactions]=useState(initialTransactions),[methods,setMethods]=useState<Method[]>([]),[method,setMethod]=useState("easypaisa"),[amount,setAmount]=useState(1000),[reference,setReference]=useState(""),[proof,setProof]=useState<File|null>(null),[status,setStatus]=useState(""),[busy,setBusy]=useState(false),[copied,setCopied]=useState("");const fileRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{fetch("/api/payments/manual").then(r=>r.json()).then(d=>setMethods(d.methods||[])).catch(()=>undefined)},[]);const selected=methods.find(m=>m.id===method);
 async function copyValue(value:string,key:string){try{await navigator.clipboard.writeText(value);setCopied(key);window.setTimeout(()=>setCopied(""),1600)}catch{setStatus("Copy was blocked. Select the detail and copy it manually.")}}
 async function refresh(){const r=await fetch("/api/wallet");if(r.ok){const d=await r.json();setWallet(d.wallet);setTransactions(d.transactions||[])}}
 async function submit(e:FormEvent){e.preventDefault();if(!proof)return setStatus("Add your payment receipt before submitting.");setBusy(true);setStatus("");const fd=new FormData();fd.append("method",method);fd.append("amount",String(amount));fd.append("transactionReference",reference);fd.append("proof",proof);const r=await fetch("/api/payments/manual",{method:"POST",body:fd});const d=await r.json().catch(()=>({}));setBusy(false);if(!r.ok)return setStatus(d.error||"Could not submit payment.");setStatus(`Payment ${d.payment.public_id} was submitted for review.`);setReference("");setProof(null);if(fileRef.current)fileRef.current.value="";await refresh()}
 const cards=[{label:"Available",value:wallet.available,detail:"Ready to use",icon:CreditCard,primary:true},{label:"Purchased",value:wallet.purchased,detail:"Never expires",icon:CheckCircle},{label:"Promotional",value:wallet.promo,detail:"Tracked separately",icon:Receipt},{label:"Reserved",value:wallet.reserved,detail:"Held for active jobs",icon:Clock}];
 return <div className="wallet-workspace"><section className="wallet-balance-grid" aria-label="Wallet balances">{cards.map(c=>{const Icon=c.icon;return <div className={`card wallet-balance-card ${c.primary?"is-primary":""}`} key={c.label}><span className="wallet-balance-icon"><Icon weight="fill"/></span><span className="wallet-balance-label">{c.label}</span><strong>{Number(c.value).toFixed(2)}</strong><small>{c.detail}</small></div>})}</section>
 <section className="wallet-topup-shell"><header className="wallet-topup-head"><div><span className="kicker">Add credits</span><h2>Top up with a bank transfer</h2><p>One credit equals PKR 1. Follow the steps and we’ll notify you after verification.</p></div><span className="wallet-review-badge"><Clock weight="fill"/>Manual review</span></header><div className="wallet-steps"><span className="is-current"><b>1</b><i>Amount</i></span><span><b>2</b><i>Transfer</i></span><span><b>3</b><i>Proof</i></span></div>
 <form className="wallet-payment-grid" onSubmit={submit}><div className="wallet-payment-form"><FormSection step="01" title="Choose your amount" detail="Minimum PKR 500"><label className="wallet-amount-field"><span>PKR</span><input type="number" min={500} step={100} value={amount} onChange={e=>setAmount(Number(e.target.value))}/><small>{Math.max(0,amount).toLocaleString()} credits</small></label><div className="wallet-amount-chips">{suggested.map(v=><button type="button" className={amount===v?"active":""} onClick={()=>setAmount(v)} key={v}>PKR {v.toLocaleString()}</button>)}</div></FormSection>
 <FormSection step="02" title="Select where to transfer" detail="Choose your preferred payment method"><div className="wallet-method-grid" role="radiogroup">{[{id:"easypaisa",name:"Easypaisa",mark:"e",tone:"easy",caption:"Mobile wallet"},{id:"meezan",name:"Meezan Bank",mark:"M",tone:"meezan",caption:"Bank transfer"}].map(x=><button type="button" role="radio" aria-checked={method===x.id} className={`wallet-method ${method===x.id?"active":""}`} onClick={()=>setMethod(x.id)} key={x.id}><span className={`wallet-method-logo ${x.tone}`}>{x.mark}</span><span><strong>{x.name}</strong><small>{x.caption}</small></span>{method===x.id&&<Check weight="bold"/>}</button>)}</div></FormSection>
 <FormSection step="03" title="Add transfer proof" detail="Use the reference from your receipt"><label className="label">Transaction / reference ID<input className="input" value={reference} onChange={e=>setReference(e.target.value)} required minLength={4} placeholder="e.g. 12345678901"/></label><input ref={fileRef} className="wallet-file-native" id="wallet-proof" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={e=>setProof(e.target.files?.[0]||null)} required/><label className={`wallet-proof-drop ${proof?"has-file":""}`} htmlFor="wallet-proof"><span><FileArrowUp weight="duotone"/></span><div><strong>{proof?proof.name:"Upload payment receipt"}</strong><small>{proof?"Ready to submit · click to replace":"PNG, JPG, WebP or PDF"}</small></div><b>{proof?"Change":"Browse"}</b></label></FormSection></div>
 <aside className="wallet-transfer-card"><div className="wallet-transfer-brand"><span className={`wallet-method-logo ${method==="meezan"?"meezan":"easy"}`}>{method==="meezan"?"M":"e"}</span><div><small>Transfer via</small><strong>{selected?.label||(method==="meezan"?"Meezan Bank":"Easypaisa")}</strong></div><span className="wallet-secure"><ShieldCheck weight="fill"/>Verified details</span></div><div className="wallet-exact-amount"><small>Send this exact amount</small><strong>PKR {Math.max(0,amount).toLocaleString()}</strong><span>You’ll receive the same number of credits.</span></div>{selected?<div className="wallet-account-details"><CopyRow label="Account title" value={selected.accountTitle} id="title" copied={copied} copyValue={copyValue}/><CopyRow label={selected.iban?"Account number":"Mobile account"} value={selected.accountNumber} id="account" copied={copied} copyValue={copyValue}/>{selected.iban&&<CopyRow label="IBAN" value={selected.iban} id="iban" copied={copied} copyValue={copyValue}/>}</div>:<div className="wallet-account-loading">Loading secure payment details…</div>}<div className="wallet-transfer-note"><Info weight="fill"/><span>{selected?.instructions||"Transfer the exact amount, then return with your transaction ID and receipt."}</span></div><button className="btn btn-primary wallet-submit" disabled={busy||amount<500}><UploadSimple weight="bold"/>{busy?"Submitting securely…":`Submit PKR ${Math.max(0,amount).toLocaleString()} payment`}</button><p className="wallet-submit-help"><ShieldCheck weight="fill"/>Credits are added only after payment verification.</p>{status&&<div className="wallet-status" role="status">{status}</div>}</aside></form></section>
 <section className="wallet-protection-strip"><div><ShieldCheck weight="fill"/><span><b>Credits never expire</b><small>Your purchased balance stays yours.</small></span></div><div><Wallet weight="fill"/><span><b>Protected spending</b><small>Reservations prevent a negative balance.</small></span></div><div><Receipt weight="fill"/><span><b>Clear ledger</b><small>Every movement is recorded below.</small></span></div></section>
 <section className="wallet-ledger"><div className="wallet-ledger-heading"><span><Receipt weight="fill"/><span><span className="kicker">Receipts</span><h2 className="page-title">Recent transactions</h2></span></span><small>Every movement is recorded</small></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Type</th><th>Amount</th><th>Balance after</th><th>Reference</th></tr></thead><tbody>{transactions.length?transactions.map(t=><tr key={t.id}><td>{new Date(t.created_at).toLocaleString()}</td><td>{t.type}</td><td style={{color:Number(t.amount)>=0?"var(--success)":"var(--text)"}}>{Number(t.amount)>=0?"+":""}{Number(t.amount).toFixed(4)}</td><td>{t.balance_after==null?"—":Number(t.balance_after).toFixed(4)}</td><td>{t.reference_id||"—"}</td></tr>):<tr><td colSpan={5} className="muted">No transactions yet.</td></tr>}</tbody></table></div></section></div>}
function FormSection({step,title,detail,children}:{step:string;title:string;detail:string;children:React.ReactNode}){return <section className="wallet-form-section"><div className="wallet-form-title"><span>{step}</span><div><h3>{title}</h3><p>{detail}</p></div></div>{children}</section>}
function CopyRow({label,value,id,copied,copyValue}:{label:string;value:string;id:string;copied:string;copyValue:(v:string,k:string)=>void}){return <div className="wallet-copy-row"><span><small>{label}</small><strong>{value}</strong></span><button type="button" onClick={()=>copyValue(value,id)}>{copied===id?<Check weight="bold"/>:<Copy weight="bold"/>}{copied===id?"Copied":"Copy"}</button></div>}

