"use client";

import { useEffect, useMemo, useState } from "react";
import { Bell, CaretRight, Check, DotsThree, FileText, FunnelSimple, Headphones, ImageSquare, MagnifyingGlass, ShieldCheck, Wallet, WarningCircle, Waveform } from "@phosphor-icons/react";

type Notification={id:string;type?:string|null;title:string;body:string;href?:string|null;read_at?:string|null;created_at:string};
type Filter="all"|"unread"|"payments"|"generations"|"wallet"|"support";
type Kind="payment"|"generation"|"wallet"|"support"|"security"|"file"|"warning"|"info";

function classify(item:Notification):Kind{const text=`${item.type||""} ${item.title} ${item.body}`.toLowerCase();if(/support|ticket|reply/.test(text))return "support";if(/security|login|secure/.test(text))return "security";if(/upload|file|document/.test(text))return "file";if(/attention|reject|failed|fail/.test(text))return "warning";if(/wallet|credit|adjustment/.test(text))return "wallet";if(/payment|pay-/.test(text))return "payment";if(/generation|image|video|audio|job/.test(text))return "generation";return "info"}
const iconFor={payment:Wallet,generation:ImageSquare,wallet:Wallet,support:Headphones,security:ShieldCheck,file:FileText,warning:WarningCircle,info:Bell};
const date=(value:string)=>new Intl.DateTimeFormat(undefined,{month:"numeric",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit",second:"2-digit"}).format(new Date(value));

export function NotificationsClient(){
 const [items,setItems]=useState<Notification[]>([]),[loading,setLoading]=useState(true),[query,setQuery]=useState(""),[filter,setFilter]=useState<Filter>("all");
 async function load(){setLoading(true);const response=await fetch("/api/notifications");if(response.ok)setItems((await response.json()).notifications||[]);setLoading(false)}
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[]);
 async function markRead(id?:string){await fetch("/api/notifications",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(id?{id}:{all:true})});await load()}
 const counts=useMemo(()=>({unread:items.filter(item=>!item.read_at).length,payments:items.filter(item=>classify(item)==="payment").length,generations:items.filter(item=>classify(item)==="generation").length,support:items.filter(item=>classify(item)==="support").length}),[items]);
 const needle=query.trim().toLowerCase();const shown=useMemo(()=>items.filter(item=>{const kind=classify(item);if(filter==="unread"&&item.read_at)return false;if(filter==="payments"&&kind!=="payment")return false;if(filter==="generations"&&kind!=="generation")return false;if(filter==="wallet"&&kind!=="wallet")return false;if(filter==="support"&&kind!=="support")return false;return !needle||`${item.title} ${item.body} ${item.type||""}`.toLowerCase().includes(needle)}),[items,filter,needle]);
 const summary=[{label:"Unread notifications",value:counts.unread,filter:"unread" as Filter,kind:"info" as Kind},{label:"Payment updates",value:counts.payments,filter:"payments" as Filter,kind:"payment" as Kind},{label:"Generation completions",value:counts.generations,filter:"generations" as Filter,kind:"generation" as Kind},{label:"Support messages",value:counts.support,filter:"support" as Filter,kind:"support" as Kind}];
 return <main className="notifications-page"><header className="notifications-hero"><div><div className="kicker">Notifications</div><h1>Updates that matter.</h1><p>Payments, wallet activity, generation results, support and security notices.</p></div><small>Build<br/>Create<br/>Go further.</small></header><section className="notification-summary" aria-label="Notification summary">{summary.map(card=>{const Icon=iconFor[card.kind];return <button type="button" className={`notification-summary-card ${card.kind}`} key={card.label} onClick={()=>setFilter(card.filter)}><span><Icon weight="fill"/></span><b>{card.value}<small>{card.label}</small></b><CaretRight weight="bold"/></button>})}</section><section className="notification-tools"><div className="notification-filters" aria-label="Notification filters">{(["all","unread","payments","generations","wallet","support"] as Filter[]).map(item=><button type="button" className={filter===item?"active":""} key={item} onClick={()=>setFilter(item)}>{item==="unread"?`Unread (${counts.unread})`:item[0].toUpperCase()+item.slice(1)}</button>)}</div><div className="notification-actions"><label><MagnifyingGlass/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search notifications…" aria-label="Search notifications"/></label><button type="button" className="notification-filter-button" aria-label="Notification filter options" onClick={()=>setFilter(filter==="unread"?"all":"unread")}><FunnelSimple weight="bold"/></button><button type="button" className="notification-mark-all" onClick={()=>void markRead()} disabled={!counts.unread}><Check weight="bold"/>Mark all read</button></div></section><section className="notification-list" aria-live="polite">{loading?<div className="notifications-empty">Loading notifications…</div>:shown.length?shown.map(item=><NotificationRow item={item} key={item.id} onRead={markRead}/>):<div className="notifications-empty"><Bell weight="duotone"/><h2>{query||filter!=="all"?"No matching notifications":"You’re all caught up"}</h2><p>{query||filter!=="all"?"Try another search or reset your filters.":"New workspace activity will appear here."}</p>{(query||filter!=="all")&&<button type="button" onClick={()=>{setQuery("");setFilter("all")}}>Clear filters</button>}</div>}</section></main>
}

function NotificationRow({item,onRead}:{item:Notification;onRead:(id?:string)=>Promise<void>}){const kind=classify(item),Icon=iconFor[kind],unread=!item.read_at;return <button type="button" className={`notification-row ${unread?"is-unread":""} ${kind}`} onClick={()=>void onRead(item.id)}><i aria-label={unread?"Unread notification":undefined}/><span className="notification-kind"><Icon weight="fill"/></span><span className="notification-copy"><b>{item.title}</b><small>{item.body}</small></span>{unread&&<em>New</em>}<time>{date(item.created_at)}</time><DotsThree weight="bold" aria-hidden="true"/></button>}
